# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'

  - script: |
      npm install
      npm run build
    displayName: 'Build React App'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'ASP-AlexTestgroup-9c30'
      appName: 'AlexTest'
      package: '$(System.DefaultWorkingDirectory)/build'
